name = "Devicons"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE"
description = "Add a shortcode to display devicons in your hugo site"
homepage = "http://ryuichirosuzuki.com/"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Ryuichiro Suzuki"
  homepage = "http://ryuichirosuzuki.com/"
